package com.broker.social_companion_system.global_services;

public enum RequestType {
    CLIENT_CONNECTED,
    CLIENT_DISCONNECTED,
    SERVER_CONNECTED,
    SERVER_DISCONNECTED,
    OPERATOR_CONNECTED,
    OPERATOR_DISCONNECTED,
    QUERY_RECEIVED,
    QUERY_CLASSIFIED_SERVICE,
    QUERY_CLASSIFIED_TASK,
    QUERY_SENT_OPERATOR,
    QUERY_SENT_SERVER,
    OPERATOR_APPROVED,
    OPERATOR_REJECTED,
    QUERY_COMPLETED

}
